//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alstar.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_faq
    {
        public int faq_id { get; set; }
        public string faq_question { get; set; }
        public string faq_answer { get; set; }
        public string faq_exp { get; set; }
        public string faq_question_en { get; set; }
        public string faq_answer_en { get; set; }
        public Nullable<int> faq_lang { get; set; }
    }
}
