//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alstar.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_article
    {
        public int article_id { get; set; }
        public string article_title { get; set; }
        public string article_date { get; set; }
        public string article_summery { get; set; }
        public string article_img { get; set; }
        public string article_img_alt { get; set; }
        public string article_exp { get; set; }
        public string article_img_width { get; set; }
        public string article_img_height { get; set; }
        public string article_writer { get; set; }
        public Nullable<int> article_visit { get; set; }
        public Nullable<int> article_type { get; set; }
        public string article_img2 { get; set; }
        public string article_img3 { get; set; }
        public string article_file { get; set; }
        public string article_href { get; set; }
        public string article_code { get; set; }
        public Nullable<int> article_lang { get; set; }
    }
}
