//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alstar.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_gallery
    {
        public int gallery_id { get; set; }
        public string gallery_title { get; set; }
        public string gallery_date { get; set; }
        public Nullable<short> gallery_is_fa { get; set; }
        public string gallery_image { get; set; }
        public Nullable<int> gallery_visit { get; set; }
        public string gallery_alt { get; set; }
        public string gallery_img_width { get; set; }
        public string gallery_img_height { get; set; }
        public string gallery_summery { get; set; }
        public string gallery_exp { get; set; }
        public string gallery_summery_en { get; set; }
        public string gallery_exp_en { get; set; }
        public Nullable<int> gallery_cat { get; set; }
        public string gallery_title_en { get; set; }
        public Nullable<int> gallery_lang { get; set; }
    }
}
