//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alstar.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_center
    {
        public int center_id { get; set; }
        public string center_title { get; set; }
        public Nullable<int> center_cat { get; set; }
        public string center_info { get; set; }
        public string center_img { get; set; }
        public string center_city { get; set; }
    }
}
