//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alstar.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_video
    {
        public int video_id { get; set; }
        public string video_title { get; set; }
        public string video_date { get; set; }
        public string video_href { get; set; }
        public string video_alt { get; set; }
        public Nullable<long> video_code { get; set; }
        public Nullable<int> video_lang { get; set; }
    }
}
