//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alstar.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customer_feedback
    {
        public int cust_feedback_id { get; set; }
        public string cust_feedback_title { get; set; }
        public string cust_feedback_exp { get; set; }
        public string cust_feedback_img { get; set; }
        public string cust_company_title { get; set; }
        public string cust_address { get; set; }
        public string cust_feedback_img_width { get; set; }
        public string cust_feedback_img_height { get; set; }
        public string cust_feedback_project_img { get; set; }
        public Nullable<int> cust_feedback_lang { get; set; }
    }
}
