//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alstar.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public int product_id { get; set; }
        public string product_title { get; set; }
        public string product_img1 { get; set; }
        public string product_img_alt { get; set; }
        public string product_price { get; set; }
        public string product_exp { get; set; }
        public string product_summery { get; set; }
        public Nullable<int> product_cat { get; set; }
        public string product_save { get; set; }
        public Nullable<int> product_exist { get; set; }
        public int product_visit { get; set; }
        public string product_img2 { get; set; }
        public string product_title1 { get; set; }
        public string product_title2 { get; set; }
        public Nullable<int> product_parent { get; set; }
        public Nullable<int> product_lang { get; set; }
    }
}
