//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alstar.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_news
    {
        public int news_id { get; set; }
        public string news_title { get; set; }
        public string news_image { get; set; }
        public int news_visit { get; set; }
        public Nullable<short> news_index { get; set; }
        public string news_date { get; set; }
        public Nullable<int> news_category { get; set; }
        public string news_exp { get; set; }
        public string news_summery { get; set; }
        public string news_writer { get; set; }
        public string news_img_alt { get; set; }
        public string news_href { get; set; }
        public string news_code { get; set; }
        public Nullable<int> news_lang { get; set; }
    }
}
