//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alstar.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_about
    {
        public int about_us_id { get; set; }
        public string about_us_img { get; set; }
        public string about_us_exp_one { get; set; }
        public string about_us_exp_two { get; set; }
        public string about_us_title { get; set; }
        public string about_us_img_width { get; set; }
        public string about_us_img_height { get; set; }
        public string about_us_img_alt { get; set; }
        public Nullable<int> about_us_type { get; set; }
        public string about_exp_en_two { get; set; }
        public string about_exp_en_one { get; set; }
        public string about_summery { get; set; }
        public Nullable<int> about_lang { get; set; }
        public Nullable<int> about_type { get; set; }
    }
}
