//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alstar.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customer
    {
        public long user_id { get; set; }
        public string user_name { get; set; }
        public string user_email { get; set; }
        public string user_text { get; set; }
        public string user_subject { get; set; }
        public string user_phone { get; set; }
        public string user_date { get; set; }
        public string user_pp_id { get; set; }
    }
}
